export const documentTypesSeed = [
  { key: "passport", requiresExpiration: true, sortOrder: 1 },
  { key: "personal_photo", requiresExpiration: false, sortOrder: 2 },
  { key: "high_school_certificate", requiresExpiration: false, sortOrder: 3 },
  { key: "high_school_transcript", requiresExpiration: false, sortOrder: 4 },
  { key: "bachelors_diploma", requiresExpiration: false, sortOrder: 5 },
  { key: "bachelors_transcript", requiresExpiration: false, sortOrder: 6 },
  { key: "masters_diploma", requiresExpiration: false, sortOrder: 7 },
  { key: "language_certificate", requiresExpiration: true, sortOrder: 8 },
  { key: "cv", requiresExpiration: false, sortOrder: 9 },
  { key: "recommendation_letter", requiresExpiration: false, sortOrder: 10 },
  { key: "motivation_letter", requiresExpiration: false, sortOrder: 11 },
  { key: "statement_of_purpose", requiresExpiration: false, sortOrder: 12 },
  { key: "work_experience", requiresExpiration: false, sortOrder: 13 },
  { key: "financial_documents", requiresExpiration: true, sortOrder: 14 },
  { key: "visa_documents", requiresExpiration: true, sortOrder: 15 },
  { key: "other", requiresExpiration: false, sortOrder: 16 },
] as const;

export const leadSourcesSeed = [
  { key: "website", name: "Website" },
  { key: "whatsapp", name: "WhatsApp" },
  { key: "instagram", name: "Instagram" },
  { key: "facebook", name: "Facebook" },
  { key: "tiktok", name: "TikTok" },
  { key: "google_ads", name: "Google Ads" },
  { key: "referral", name: "Referral" },
  { key: "educational_agent", name: "Educational Agent" },
  { key: "event", name: "Event" },
  { key: "organic_search", name: "Organic Search" },
  { key: "university_partner", name: "University Partner" },
  { key: "manual_entry", name: "Manual Entry" },
] as const;

export const rolesSeed = [
  { key: "super_admin", name: "Super Administrator" },
  { key: "general_manager", name: "General Manager" },
  { key: "operations_manager", name: "Operations Manager" },
  { key: "consultant", name: "Educational Consultant" },
  { key: "admissions_officer", name: "Admissions Officer" },
  { key: "sales_representative", name: "Sales Representative" },
  { key: "marketing_manager", name: "Marketing Manager" },
  { key: "content_editor", name: "Content Editor" },
  { key: "finance_officer", name: "Finance Officer" },
  { key: "student_support_officer", name: "Student Support Officer" },
  { key: "quality_analytics_officer", name: "Quality and Analytics Officer" },
  { key: "student", name: "Student" },
  { key: "partner_rep", name: "University Partner Representative" },
  { key: "agent", name: "Educational Agent" },
] as const;

// Module.action — enforced server-side per docs/02-roles-and-permissions.md.
export const permissionsSeed = [
  "leads.manage",
  "leads.view_own",
  "students.manage",
  "students.view_own",
  "applications.manage",
  "applications.view_own",
  "applications.update_status",
  "documents.verify",
  "documents.upload_own",
  "universities.manage",
  "programs.manage",
  "scholarships.manage",
  "content.manage",
  "staff.manage",
  "roles.manage",
  "finance.manage",
  "finance.view_own",
  "reports.view",
  "reports.view_own",
  "activity_logs.view",
  "messaging.manage",
  "appointments.manage",
] as const;
