export interface ScholarshipSeed {
  slug: string;
  universitySlug?: string;
  countrySlug?: string;
  coverageType: "FULL" | "PARTIAL";
  coveragePercent?: number;
  fundingType: string;
  deadline: string; // ISO date
  eligibleDegreeLevels: string[];
  eligibleNationalities: string[];
  title: string;
  providerName: string;
  eligibilityText: string;
  requiredDocumentsNote: string;
  applicationProcess: string;
  termsAndConditions: string;
}

// [DEMO DATA]
export const scholarshipsSeed: ScholarshipSeed[] = [
  {
    slug: "full-scholarship-turkiye",
    countrySlug: "turkiye",
    coverageType: "FULL",
    fundingType: "Government",
    deadline: "2026-09-30",
    eligibleDegreeLevels: ["BACHELORS", "MASTERS", "PHD"],
    eligibleNationalities: ["All nationalities"],
    title: "Türkiye Bilim Full Scholarship",
    providerName: "Türkiye Ministry of Education",
    eligibilityText: "Open to international students with a minimum GPA of 3.0 applying to partner Turkish universities.",
    requiredDocumentsNote: "Transcript, passport copy, motivation letter, two recommendation letters.",
    applicationProcess: "Apply through FastUniApply; consultant reviews eligibility before submission to the ministry portal.",
    termsAndConditions: "Renewable annually subject to maintaining a minimum GPA of 2.5.",
  },
  {
    slug: "central-european-partial-award",
    universitySlug: "eotvos-lorand-university",
    coverageType: "PARTIAL",
    coveragePercent: 50,
    fundingType: "University",
    deadline: "2026-08-15",
    eligibleDegreeLevels: ["MASTERS"],
    eligibleNationalities: ["All nationalities"],
    title: "Central European Partial Award",
    providerName: "Eötvös Loránd University",
    eligibilityText: "Awarded to Master's applicants with a strong undergraduate academic record.",
    requiredDocumentsNote: "Transcript, CV, statement of purpose.",
    applicationProcess: "Automatically considered upon program application submission.",
    termsAndConditions: "Valid for the standard program duration only.",
  },
  {
    slug: "debrecen-medicine-merit-award",
    universitySlug: "university-of-debrecen",
    coverageType: "PARTIAL",
    coveragePercent: 20,
    fundingType: "University",
    deadline: "2026-07-31",
    eligibleDegreeLevels: ["MEDICAL_SPECIALIZATION"],
    eligibleNationalities: ["All nationalities"],
    title: "Debrecen Medicine Merit Award",
    providerName: "University of Debrecen",
    eligibilityText: "For entrance-exam applicants scoring in the top 15%.",
    requiredDocumentsNote: "Entrance exam result, secondary school certificate.",
    applicationProcess: "Awarded automatically based on entrance exam ranking.",
    termsAndConditions: "Subject to continued good academic standing.",
  },
  {
    slug: "tum-excellence-scholarship",
    universitySlug: "technical-university-of-munich",
    coverageType: "PARTIAL",
    coveragePercent: 30,
    fundingType: "University",
    deadline: "2026-05-31",
    eligibleDegreeLevels: ["MASTERS", "PHD"],
    eligibleNationalities: ["All nationalities"],
    title: "TUM Excellence Scholarship",
    providerName: "Technical University of Munich",
    eligibilityText: "For applicants with outstanding academic and research potential.",
    requiredDocumentsNote: "Research proposal (PhD) or statement of purpose (Master's), academic transcript.",
    applicationProcess: "Separate scholarship application submitted alongside the program application.",
    termsAndConditions: "Renewable each semester subject to progress review.",
  },
  {
    slug: "warsaw-international-award",
    universitySlug: "university-of-warsaw",
    coverageType: "PARTIAL",
    coveragePercent: 40,
    fundingType: "University",
    deadline: "2026-06-30",
    eligibleDegreeLevels: ["BACHELORS", "MASTERS"],
    eligibleNationalities: ["All nationalities"],
    title: "Warsaw International Award",
    providerName: "University of Warsaw",
    eligibilityText: "For international applicants demonstrating financial need and strong academics.",
    requiredDocumentsNote: "Financial statement, transcript, motivation letter.",
    applicationProcess: "Apply via the university's international office after admission.",
    termsAndConditions: "One-time award applied to the first year of tuition.",
  },
  {
    slug: "srh-berlin-early-bird-discount",
    universitySlug: "srh-berlin-university",
    coverageType: "PARTIAL",
    coveragePercent: 10,
    fundingType: "University",
    deadline: "2026-04-30",
    eligibleDegreeLevels: ["BACHELORS", "MASTERS"],
    eligibleNationalities: ["All nationalities"],
    title: "Early Application Tuition Discount",
    providerName: "SRH Berlin University of Applied Sciences",
    eligibilityText: "Applicants who complete their application at least 6 months before intake.",
    requiredDocumentsNote: "None beyond standard application documents.",
    applicationProcess: "Automatically applied at enrollment if the deadline is met.",
    termsAndConditions: "Cannot be combined with other tuition discounts.",
  },
  {
    slug: "taylors-hospitality-talent-scholarship",
    universitySlug: "taylors-university",
    coverageType: "PARTIAL",
    coveragePercent: 25,
    fundingType: "University",
    deadline: "2026-10-15",
    eligibleDegreeLevels: ["BACHELORS"],
    eligibleNationalities: ["All nationalities"],
    title: "Hospitality Talent Scholarship",
    providerName: "Taylor's University",
    eligibilityText: "For applicants to the Hospitality Management program with prior industry experience or a portfolio.",
    requiredDocumentsNote: "Portfolio or work reference letter, transcript.",
    applicationProcess: "Submit portfolio alongside the standard program application.",
    termsAndConditions: "Awarded for the full duration of study, subject to good standing.",
  },
  {
    slug: "gau-mediterranean-scholarship",
    universitySlug: "girne-american-university",
    coverageType: "PARTIAL",
    coveragePercent: 60,
    fundingType: "University",
    deadline: "2026-09-01",
    eligibleDegreeLevels: ["BACHELORS", "MASTERS"],
    eligibleNationalities: ["All nationalities"],
    title: "Mediterranean Scholarship",
    providerName: "Girne American University",
    eligibilityText: "Broad-based scholarship for new international applicants.",
    requiredDocumentsNote: "High school or Bachelor's transcript.",
    applicationProcess: "Applied automatically to all eligible applications.",
    termsAndConditions: "Requires maintaining a 2.0 GPA or above each year.",
  },
  {
    slug: "bedfordshire-global-impact-scholarship",
    universitySlug: "university-of-bedfordshire",
    coverageType: "PARTIAL",
    coveragePercent: 20,
    fundingType: "University",
    deadline: "2026-07-01",
    eligibleDegreeLevels: ["BACHELORS", "MASTERS"],
    eligibleNationalities: ["All nationalities"],
    title: "Global Impact Scholarship",
    providerName: "University of Bedfordshire",
    eligibilityText: "For students demonstrating community leadership or volunteering experience.",
    requiredDocumentsNote: "Personal statement describing community impact, one reference letter.",
    applicationProcess: "Submit alongside your program application; shortlisted applicants may be interviewed.",
    termsAndConditions: "One-time award applied to first-year tuition fees.",
  },
  {
    slug: "rome-business-school-women-in-leadership",
    universitySlug: "rome-business-school",
    coverageType: "PARTIAL",
    coveragePercent: 35,
    fundingType: "University",
    deadline: "2026-11-30",
    eligibleDegreeLevels: ["MASTERS"],
    eligibleNationalities: ["All nationalities"],
    title: "Women in Leadership Scholarship",
    providerName: "Rome Business School",
    eligibilityText: "For women applicants to the MBA or Marketing Management programs demonstrating leadership potential.",
    requiredDocumentsNote: "CV, leadership essay, two references.",
    applicationProcess: "Submit the leadership essay via the FastUniApply application wizard.",
    termsAndConditions: "Awarded once per cohort; non-transferable.",
  },
  {
    slug: "krakow-economics-cee-scholarship",
    universitySlug: "krakow-university-of-economics",
    coverageType: "PARTIAL",
    coveragePercent: 30,
    fundingType: "University",
    deadline: "2026-06-15",
    eligibleDegreeLevels: ["BACHELORS", "MASTERS"],
    eligibleNationalities: ["Central & Eastern Europe", "Central Asia"],
    title: "CEE Regional Scholarship",
    providerName: "Krakow University of Economics",
    eligibilityText: "For applicants from Central & Eastern European or Central Asian countries.",
    requiredDocumentsNote: "Passport copy, transcript.",
    applicationProcess: "Automatically assessed based on nationality at application.",
    termsAndConditions: "Valid for the standard program duration.",
  },
];
