services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastuniapply
    ports:
      - "5432:5432"
    volumes:
      - fastuniapply_postgres_data:/var/lib/postgresql/data

volumes:
  fastuniapply_postgres_data:
